#!/bin/bash
PATH="./node_modules/.bin/:$PATH"

install_client() {
  npm install
  elm-package install -y
}

install_server() {
  sbt update
}

install() {
  install_client
  install_server
}

package_client() {
  elm-make src/main/elm/Main.elm --output src/main/resources/web/static/index.js
}

package_server() {
  sbt package
}

package() {
  package_client
  package_server
}

run_server() {
  sbt 'run com.benpence.blog.server.MainBlogServer
    -file.posts data/posts.yaml
    -file.users data/users.yaml
    --
    -local.doc.root=src/main/resources/web/
    '
}

run() {
  package
  run_server
}

die() {
  local exit_code="$1" && shift
  local message="$1" && shift

  echo $message 1>&2
  exit ${exit_code}
}

check_dependency() {
  local command="$1" && shift
  which "$command" >&- || die 1 "Cannot find '$command' on path"
}

check_dependencies() {
  check_dependency npm
  check_dependency sbt
  check_dependency scalac
}

main() {
  local command="$1" && shift

  check_dependencies

  case "$command" in
    "install_client") install_client ;;
    "install_server") install_server ;;
    "install")        install ;;
    "package_client") package_client ;;
    "package_server") package_server ;;
    "package")        package ;;
    "run_server")     run_server ;;
    "run")            run ;;
    *) die 1 "Unrecognized command \"$command\""
  esac
}

set -eu
main $@
