#!/bin/bash
PATH="$PATH:./node_modules/.bin/"

install() {
  npm install --no-optional
  bower install
}

build_client() {
  pulp build -O --to src/main/resources/web/static/index.js
}

build_server() {
  sbt package
}

build() {
  build_client
  build_server
}

run() {
  build_client

  sbt 'run com.benpence.blog.server.MainBlogServer
    -file.posts data/posts.yaml
    -file.users data/users.yaml
    --
    -local.doc.root=src/main/resources/web/
    '
}

die() {
  local exit_code="$1" && shift
  local message="$1" && shift

  echo $message 1>&2
  exit ${exit_code}
}

check_dependency() {
  local command="$1" && shift
  which "$command" >&- || die 1 "Cannot find '$command' on path"
}

check_dependencies() {
  check_dependency sbt
  check_dependency scalac
}

main() {
  local command="$1" && shift

  check_dependencies

  case "$command" in
    "install") npm install ;;
    "package") package ;;
    "build-client") build_client ;;
    "build-server") build_client ;;
    "run") run ;;
    *) echo "Unrecognized command \"$command\""; exit 1 ;;
  esac
}

set -eu
main $@
